# @package _global_

defaults:
  - _self_
  - data: til_permuted_mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: til_mlp_finetuning.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

experiment_name: "eval"

tags: ["example", "default_experiment"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
